# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrsd32.a
  DEFINES   += -DDEBUG -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m32 -L/usr/lib32 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimcd32.a -lm -lpthread
  LDDEPS    += ../../bin/libsimcd32.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs32.a
  DEFINES   += -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -g -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m32 -L/usr/lib32 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc32.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc32.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debugdynamic32)
  OBJDIR     = obj/x32/DebugDynamic/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrsd32.so
  DEFINES   += -DDEBUG -DEVDS_DYNAMIC -DIVSS_DYNAMIC -DRDRS_DYNAMIC -DSIMC_DYNAMIC -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -shared -m32 -L/usr/lib32 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimcd32.a -lm -lpthread
  LDDEPS    += ../../bin/libsimcd32.a
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),releasedynamic32)
  OBJDIR     = obj/x32/ReleaseDynamic/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs32.so
  DEFINES   += -DEVDS_DYNAMIC -DIVSS_DYNAMIC -DRDRS_DYNAMIC -DSIMC_DYNAMIC -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -g -m32 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -shared -m32 -L/usr/lib32 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc32.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc32.a
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debugsinglethread32)
  OBJDIR     = obj/x32/DebugSingleThread/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs_std32.a
  DEFINES   += -DDEBUG -DEVDS_SINGLETHREADED -DIVSS_SINGLETHREADED -DRDRS_SINGLETHREADED -DSIMC_SINGLETHREADED -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m32 -L/usr/lib32 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc_std32.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc_std32.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),releasesinglethread32)
  OBJDIR     = obj/x32/ReleaseSingleThread/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs_st32.a
  DEFINES   += -DEVDS_SINGLETHREADED -DIVSS_SINGLETHREADED -DRDRS_SINGLETHREADED -DSIMC_SINGLETHREADED -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -g -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m32 -L/usr/lib32 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc_st32.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc_st32.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debugsinglethreaddynamic32)
  OBJDIR     = obj/x32/DebugSingleThreadDynamic/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs_std32.so
  DEFINES   += -DDEBUG -DEVDS_DYNAMIC -DIVSS_DYNAMIC -DRDRS_DYNAMIC -DSIMC_DYNAMIC -DEVDS_SINGLETHREADED -DIVSS_SINGLETHREADED -DRDRS_SINGLETHREADED -DSIMC_SINGLETHREADED -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -shared -m32 -L/usr/lib32 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc_std32.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc_std32.a
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),releasesinglethreaddynamic32)
  OBJDIR     = obj/x32/ReleaseSingleThreadDynamic/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs_st32.so
  DEFINES   += -DEVDS_DYNAMIC -DIVSS_DYNAMIC -DRDRS_DYNAMIC -DSIMC_DYNAMIC -DEVDS_SINGLETHREADED -DIVSS_SINGLETHREADED -DRDRS_SINGLETHREADED -DSIMC_SINGLETHREADED -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -g -m32 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -shared -m32 -L/usr/lib32 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc_st32.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc_st32.a
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrsd.a
  DEFINES   += -DDEBUG -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m64 -L/usr/lib64 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimcd.a -lm -lpthread
  LDDEPS    += ../../bin/libsimcd.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs.a
  DEFINES   += -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -g -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m64 -L/usr/lib64 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debugdynamic64)
  OBJDIR     = obj/x64/DebugDynamic/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrsd.so
  DEFINES   += -DDEBUG -DEVDS_DYNAMIC -DIVSS_DYNAMIC -DRDRS_DYNAMIC -DSIMC_DYNAMIC -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m64 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -shared -m64 -L/usr/lib64 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimcd.a -lm -lpthread
  LDDEPS    += ../../bin/libsimcd.a
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),releasedynamic64)
  OBJDIR     = obj/x64/ReleaseDynamic/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs.so
  DEFINES   += -DEVDS_DYNAMIC -DIVSS_DYNAMIC -DRDRS_DYNAMIC -DSIMC_DYNAMIC -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -g -m64 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -shared -m64 -L/usr/lib64 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc.a
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debugsinglethread64)
  OBJDIR     = obj/x64/DebugSingleThread/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs_std.a
  DEFINES   += -DDEBUG -DEVDS_SINGLETHREADED -DIVSS_SINGLETHREADED -DRDRS_SINGLETHREADED -DSIMC_SINGLETHREADED -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m64 -L/usr/lib64 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc_std.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc_std.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),releasesinglethread64)
  OBJDIR     = obj/x64/ReleaseSingleThread/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs_st.a
  DEFINES   += -DEVDS_SINGLETHREADED -DIVSS_SINGLETHREADED -DRDRS_SINGLETHREADED -DSIMC_SINGLETHREADED -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -g -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -m64 -L/usr/lib64 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc_st.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc_st.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debugsinglethreaddynamic64)
  OBJDIR     = obj/x64/DebugSingleThreadDynamic/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs_std.so
  DEFINES   += -DDEBUG -DEVDS_DYNAMIC -DIVSS_DYNAMIC -DRDRS_DYNAMIC -DSIMC_DYNAMIC -DEVDS_SINGLETHREADED -DIVSS_SINGLETHREADED -DRDRS_SINGLETHREADED -DSIMC_SINGLETHREADED -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m64 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -shared -m64 -L/usr/lib64 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc_std.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc_std.a
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),releasesinglethreaddynamic64)
  OBJDIR     = obj/x64/ReleaseSingleThreadDynamic/rdrs
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/librdrs_st.so
  DEFINES   += -DEVDS_DYNAMIC -DIVSS_DYNAMIC -DRDRS_DYNAMIC -DSIMC_DYNAMIC -DEVDS_SINGLETHREADED -DIVSS_SINGLETHREADED -DRDRS_SINGLETHREADED -DSIMC_SINGLETHREADED -DRDRS_LIBRARY -DSIMC_LIBRARY
  INCLUDES  += -I../../include -I../../external/simc/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -g -m64 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -shared -m64 -L/usr/lib64 -lstdc++
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libsimc_st.a -lm -lpthread
  LDDEPS    += ../../bin/libsimc_st.a
  LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/rdrs_antenna.o \
	$(OBJDIR)/rdrs_lookup.o \
	$(OBJDIR)/rdrs_physics.o \
	$(OBJDIR)/rdrs_system.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking rdrs
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning rdrs
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	-$(SILENT) cp $< $(OBJDIR)
else
	$(SILENT) xcopy /D /Y /Q "$(subst /,\,$<)" "$(subst /,\,$(OBJDIR))" 1>nul
endif
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
endif

$(OBJDIR)/rdrs_antenna.o: ../../source/rdrs_core/rdrs_antenna.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdrs_lookup.o: ../../source/rdrs_core/rdrs_lookup.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdrs_physics.o: ../../source/rdrs_core/rdrs_physics.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdrs_system.o: ../../source/rdrs_core/rdrs_system.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
